from datetime import timedelta

# JWT
SECRET_KEY = "CHANGE_THIS_SECRET_KEY"
ALGORITHM = "HS256"
ACCESS_TOKEN_EXPIRE_MINUTES = 60

# Registration Secret Keys
ADMIN_SECRET_KEY = "ADMIN_123"
SUPERADMIN_SECRET_KEY = "SUPERADMIN_456"
