# BragBoard - Enterprise Recognition & AI Cultural Intelligence

BragBoard is a next-generation employee engagement platform that combines social recognition with Google Gemini AI to analyze workspace sentiment, detect burnout, and moderate professional conduct. It uses a high-performance **FastAPI** backend with **SQLite** for reliable local persistence and **React** with **Tailwind CSS** for a "Cyber-Corporate" aesthetic.

---

## 📂 Project Structure

```text
/ (Project Root)
├── index.html              # Main entry HTML
├── index.tsx               # Application core & Routing
├── types.ts                # TypeScript interfaces
├── client/                 # Frontend Assets & Pages
├── server/                 # PYTHON BACKEND
│   ├── __init__.py         # Marks server as a Python package
    ├── database.py         # SQLAlchemy & SQLite setup
    ├── models.py           # Database Table definitions
    ├── schemas.py          # Pydantic data validation
    ├── auth.py             # JWT Security & Password logic
    ├── main.py             # FastAPI entry point & API endpoints
    └── bragboard.db        # Auto-created SQLite database
├── requirements.txt        # Python dependencies
└── README.md
```

---

## 🤖 Step-by-Step Backend Generation Guide

To get your backend running instantly, follow these steps to generate the code using an AI (Gemini, ChatGPT, or Claude):

### Step 1: Prepare the AI
Open your preferred AI assistant and paste the **"Master Prompt"** found in Step 2.

### Step 2: Copy & Paste this Master Prompt

> **PROMPT:**
> "I am building a professional Employee Recognition platform called **BragBoard**. I have a React frontend that communicates with a FastAPI backend at `http://localhost:8000`. 
>
> Please generate a complete, production-grade Python backend using **FastAPI**, **SQLAlchemy (SQLite)**, **Pydantic**, and **JWT Authentication**.
>
> **Project Structure (Generate 5 separate files):**
> 1. `database.py`: Setup SQLite engine and SessionLocal.
> 2. `models.py`: 
>    - `User`: id, name, email, hashed_password, role (EMPLOYEE, ADMIN, SUPER_ADMIN), department, points (default 0), avatar_url, status (ACTIVE/PENDING).
>    - `ShoutOut`: id, from_user_id, message, category, timestamp, sentiment_score, mood, is_reported (bool).
>    - `Recipients`: Association table for ShoutOut to Users.
>    - `Announcement`, `Challenge`, `Transaction`.
> 3. `schemas.py`: Pydantic models for all entities, including Auth tokens.
> 4. `auth.py`: JWT utilities (create_access_token), password hashing (Bcrypt), and OAuth2 password bearer.
> 5. `main.py`: The entry point.
>
> **CRITICAL Business Logic to include:**
> - **XP Logic**: In `POST /shoutouts`, when a brag is created, the 'sender' must get **+50 points** and every 'recipient' must get **+100 points** in the database.
> - **Security Codes**: 
>   - Registration for `ADMIN` role requires secret code 'ADMIN123'.
>   - Registration for `SUPER_ADMIN` role requires secret code 'SUPER123'.
> - **Endpoints Needed**: 
>   - `POST /auth/register`, `POST /auth/token` (Form Data for OAuth2), `GET /auth/me`.
>   - `GET/POST /shoutouts`, `GET /users`, `GET/POST /announcements`, `GET/POST /challenges`.
> - **CORS**: Enable for `http://localhost:5500` and `http://127.0.0.1:5500`.
>
> Provide the code for each file clearly labeled."

### Step 3: Create the Files
1. Create a folder in your project root named `server/`.
2. Inside `server/`, create the 5 files: `database.py`, `models.py`, `schemas.py`, `auth.py`, and `main.py`.
3. Paste the corresponding code blocks generated by the AI into each file.

---

## 🚀 Launching the System

### 1. Install Python Requirements
Run this in your terminal to install the necessary libraries:
```bash
pip install fastapi uvicorn sqlalchemy python-jose[cryptography] passlib[bcrypt] python-multipart
```

### 2. Start the Backend Server
```bash
# Run from the project root
python -m uvicorn server.main:app --reload --port 8000
```

### 3. Start the Frontend
Open `index.html` using the **Live Server** extension in VS Code (usually runs on port 5500).

---

## 📡 Database & Connectivity
- The backend will automatically create a `bragboard.db` file in your root folder.
- All recognitions, points, and user accounts will persist even if you restart your computer.
- Use the **Admin Secret Key**: `ADMIN123` during signup to access management features.
